// try
// {
//     let x = undefined;
//     console.log(x[0])
// }
// catch(err)
// {
//     console.log("error handling in catch block",err)
// }
// finally
// {
//     console.log("finally will executed in any case")
// }
// console.log("End")

try {
    console.log("hello")
    console.log(a)
}
catch {
    console.log("handled")
}
console.log("End")